name: Run linter and test

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Set up environment
      run: make setup

    - name: Run linter
      run: make lint
    
    - name: Run tests
      run: make test